redmine_issue_templates/config/routes.rb
#
# TODO: Clean up routing.
#
Rails.application.routes.draw do
  get 'projects/:project_id/issue_templates', to: 'issue_templates#index'
  match 'projects/:project_id/issue_templates/:action', controller: 'issue_templates', via: [:get, :post, :patch, :put]
  match 'projects/:project_id/issue_templates/:action/:id', to: 'issue_templates#edit', via: [:patch, :put, :post, :get]
  match 'projects/:project_id/issue_templates_settings/:action', controller: 'issue_templates_settings', via: [:get, :post, :patch, :put]
  match 'issue_templates/preview', to: 'issue_templates#preview', via: [:get, :post]
  match 'projects/:project_id/issue_templates_settings/preview', to: 'issue_templates_settings#preview', via: [:get, :post]
  get 'global_issue_templates', to: 'global_issue_templates#index'
  match 'global_issue_templates/:action', controller: 'global_issue_templates', via: [:get, :post]
  match 'global_issue_templates/:action/:id', to: 'global_issue_templates#edit', via: [:patch, :put, :post, :get]
  match 'global_issue_templates/preview', to: 'global_issue_templates#preview', via: [:get, :post]
  get 'projects/:project_id/issue_templates/orphaned_templates', to: 'issue_templates#orphaned_templates', as: 'project_orphaned_templates'
  get 'global_issue_templates/orphaned_templates', to: 'global_issue_templates#orphaned_templates', as: 'global_orphaned_templates'
end

redmine_issue_templates/app/models/concerns/issue_template/common.rb
module Concerns
  module IssueTemplate
    module Common
      extend ActiveSupport::Concern

      #
      # Common scope both global and project scope template.
      #
      included do
        belongs_to :author, class_name: 'User', foreign_key: 'author_id'
        belongs_to :tracker
        before_save :check_default

        before_destroy :confirm_disabled

        validates :title, presence: true
        validates :tracker, presence: true

        acts_as_positioned scope: [:tracker_id]

        scope :enabled, -> { where(enabled: true) }
        scope :sorted, -> { order(:position) }
        scope :search_by_tracker, lambda { |tracker_id|
          where(tracker_id: tracker_id) if tracker_id.present?
        }

        scope :is_default, -> { where(is_default: true) }
        scope :not_default, -> { where(is_default: false) }

        scope :orphaned, lambda { |project_id = nil|
          condition = all
          ids = []

          if project_id.present? && try(:name) == 'IssueTemplate'
            condition = condition.where(project_id: project_id)
            ids = Tracker.joins(:projects).where(projects: { id: project_id }).pluck(:id)
          else
            ids = Tracker.pluck(:id)
          end
          condition.where.not(tracker_id: ids)
        }

        after_destroy do |template|
          logger.info("[Destroy] #{self.class}: #{template.inspect}")
        end
      end

      #
      # Common methods both global and project scope template.
      #
      def enabled?
        enabled
      end

      def <=>(other)
        position <=> other.position
      end

      def checklist
        return [] if checklist_json.blank?
        begin
          JSON.parse(checklist_json)
        rescue
          []
        end
      end

      def template_json
        template = {}
        template[self.class::Config::JSON_OBJECT_NAME] = generate_json
        template.to_json(root: true)
      end

      def generate_json
        result = attributes
        result[:checklist] = checklist
        result.except('checklist_json')
      end

      def template_struct(option = {})
        Struct.new(:value, :name, :class, :selected).new(id, title, option[:class])
      end

      def log_destroy_action(template)
        logger.info "[Destroy] #{self.class}: #{template.inspect}" if logger && logger.info
      end

      def confirm_disabled
        return unless enabled?
        errors.add :base, 'enabled_template_cannot_destroy'
        false
      end

      def copy_title
        "copy_of_#{title}"
      end
    end
  end
end

redmine_issue_templates/app/models/issue_template.rb
class IssueTemplate < ActiveRecord::Base
  include Redmine::SafeAttributes
  include Concerns::IssueTemplate::Common
  belongs_to :project
  validates :project_id, presence: true
  validates_uniqueness_of :title, scope: :project_id

  # author and project should be stable.
  safe_attributes 'title', 'description', 'tracker_id', 'note', 'enabled', 'issue_title', 'is_default',
                  'enabled_sharing', 'visible_children', 'position'
  attr_accessible :title, :tracker_id, :issue_title, :description, :note,
                  :is_default, :enabled, :enabled_sharing, :author, :project, :position

  scope :enabled_sharing, -> { where(enabled_sharing: true) }
  scope :search_by_project, lambda { |prolect_id|
    where(project_id: prolect_id)
  }

  module Config
    JSON_OBJECT_NAME = 'issue_template'.freeze
  end
  Config.freeze

  #
  # In case set is_default and updated, others are also updated.
  #
  def check_default
    return unless is_default? && is_default_changed?
    self.class.search_by_project(project_id).search_by_tracker(tracker_id).update_all(is_default: false)
  end

  # return projects that use this template
  def used_projects
    return [] unless enabled_sharing
    projects = project.descendants
                      .joins(:trackers, :enabled_modules).merge(Tracker.where(id: tracker_id)).merge(EnabledModule.where(name: 'issue_templates'))
    IssueTemplateSetting.where(project_id: projects).inherit_templates.select(:project_id)
  end

  #
  # Class method
  #
  class << self
    def get_inherit_templates(project_ids, tracker_id)
      # keep ordering of project tree
      IssueTemplate.search_by_project(project_ids)
                   .search_by_tracker(tracker_id)
                   .enabled
                   .enabled_sharing
                   .sorted
    end

    def get_templates_for_project_tracker(project_id, tracker_id = nil)
      IssueTemplate.search_by_project(project_id)
                   .search_by_tracker(tracker_id)
                   .enabled
                   .sorted
    end
  end
end

redmine_issue_templates/app/controllers/issue_templates_controller.rb
# noinspection ALL
class IssueTemplatesController < ApplicationController
  layout 'base'
  include IssueTemplatesHelper
  helper :issues
  include IssuesHelper
  include Concerns::IssueTemplatesCommon
  menu_item :issues
  before_filter :find_object, only: [:show, :edit, :update, :destroy]
  before_filter :find_user, :find_project, :authorize, except: [:preview]
  before_filter :find_tracker, :find_templates, only: [:set_pulldown, :list_templates]
  accept_api_auth :index, :list_templates, :load

  def index
    project_id = @project.id
    project_templates = IssueTemplate.search_by_project(project_id)

    # pick up used tracker ids
    tracker_ids = @project.trackers.pluck(:id)

    @template_map = {}
    tracker_ids.each do |tracker_id|
      templates = project_templates.search_by_tracker(tracker_id).sorted
      @template_map[Tracker.find(tracker_id)] = templates if templates.any?
    end

    setting = IssueTemplateSetting.find_or_create(project_id)
    @inherit_templates = setting.get_inherit_templates

    @global_issue_templates = global_templates(tracker_ids)

    respond_to do |format|
      format.html do
        render layout: !request.xhr?, locals: { apply_all_projects: apply_all_projects? }
      end
      format.api do
        render formats: :json, locals: { project_templates: project_templates }
      end
    end
  end

  def show
    render_form
  end

  def new
    if params[:id].present?
      @issue_template = IssueTemplate.find(params[:id]).dup
      @issue_template.title = @issue_template.copy_title
    else
      # create empty instance
      @issue_template ||= IssueTemplate.new(author: @user, project: @project)
    end

    if request.post?
      @issue_template.safe_attributes = template_params
      @issue_template.checklist_json = checklists.to_json

      save_and_flash(:notice_successful_create) && return
    end
    render_form
  end

  def update
    @issue_template.safe_attributes = template_params
    @issue_template.checklist_json = checklists.to_json
    save_and_flash(:notice_successful_update)
  end

  def edit
    # Change from request.post to request.patch for Rails4.
    return unless request.patch? || request.put?
    @issue_template.safe_attributes = template_params

    @issue_template.checklist_json = checklists.to_json

    save_and_flash(:notice_successful_update)
  end

  def destroy
    return unless request.post?
    unless @issue_template.destroy
      flash[:error] = l(:enabled_template_cannot_destroy)
      redirect_to action: :show, project_id: @project, id: @issue_template
      return
    end
    flash[:notice] = l(:notice_successful_delete)
    redirect_to action: 'index', project_id: @project
  end

  # load template description
  def load
    issue_template_id = params[:issue_template]
    template_type = params[:template_type]
    issue_template = if !template_type.blank? && template_type == 'global'
                       GlobalIssueTemplate.find(issue_template_id)
                     else
                       IssueTemplate.find(issue_template_id)
                     end
    render text: issue_template.template_json
  end

  # update pulldown
  def set_pulldown
    @group = []
    @default_template = nil

    add_templates_to_group(@issue_templates)
    add_templates_to_group(@inherit_templates, class: 'inherited')
    add_templates_to_group(@global_templates, class: 'global')

    is_triggered_by_status = request.parameters[:is_triggered_by_status]
    @group[@default_template].selected = 'selected' if @default_template.present?

    render action: '_template_pulldown', layout: false,
           locals: { is_triggered_by_status: is_triggered_by_status, grouped_options: @group,
                     should_replaced: setting.should_replaced, default_template: @default_template }
  end

  #
  # List templates associated with tracker and project.
  # TODO: refactor here. Duplicate with set_pulldown....
  #
  def list_templates
    (default_global, default_inherit, default_project) = default_templates

    default_template = default_inherit.present? ? default_inherit : default_global
    default_template = default_project.present? ? default_project : default_template

    respond_to do |format|
      format.html do
        render action: '_list_templates',
               layout: false,
               locals: { default_template: default_template,
                         issue_templates: @issue_templates,
                         inherit_templates: @inherit_templates,
                         global_issue_templates: @global_templates }
      end
      format.api do
        render action: '_list_templates',
               locals: { default_template: default_template,
                         issue_templates: @issue_templates,
                         inherit_templates: @inherit_templates,
                         global_issue_templates: @global_templates }
      end
    end
  end

  # preview
  def preview
    issue_template = params[:issue_template]
    @text = (issue_template ? issue_template[:description] : nil)
    render partial: 'common/preview'
  end

  def orphaned_templates
    orphaned = IssueTemplate.orphaned(@project.id)
    render partial: 'orphaned_templates', locals: { orphaned_templates: orphaned }
  end

  private

  def find_user
    @user = User.current
  end

  def find_tracker
    @tracker = Tracker.find(params[:issue_tracker_id])
  end

  def find_object
    @issue_template = IssueTemplate.find(params[:id])
    @project = @issue_template.project
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_project
    @project = Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_templates
    @issue_templates = issue_templates
    @inherit_templates = inherit_templates
    @global_templates = global_templates(@tracker.id)
  end

  def save_and_flash(message)
    return unless @issue_template.save
    respond_to do |format|
      format.html do
        flash[:notice] = l(message)
        redirect_to action: 'show', id: @issue_template.id, project_id: @project
      end
      format.js { head 200 }
    end
  end

  def render_form
    render(layout: !request.xhr?,
           locals: { checklist_enabled: checklist_enabled?,
                     issue_template: @issue_template, project: @project })
  end

  def setting
    IssueTemplateSetting.find_or_create(@project.id)
  end

  def global_templates(tracker_id)
    if apply_all_projects? && (@inherit_templates.present? || @issue_templates.present?)
      return []
    end
    project_id = apply_all_projects? ? nil : @project.id
    GlobalIssueTemplate.get_templates_for_project_tracker(project_id, tracker_id)
  end

  def default_templates
    [@global_templates, @inherit_templates, @issue_templates].map do |templates|
      templates.try(:is_default).try(:first)
    end
  end

  def default_template_index
    @default_template.blank? ? @group.length - 1 : @default_template
  end

  def add_templates_to_group(templates, option = {})
    templates.each do |template|
      @group << template.template_struct(option)
      next unless template.is_default == true
      @default_template = default_template_index
    end
  end

  def issue_templates
    IssueTemplate.get_templates_for_project_tracker(@project.id, @tracker.id)
  end

  def inherit_templates
    setting.get_inherit_templates(@tracker)
  end

  def template_params
    params.require(:issue_template).permit(:tracker_id, :title, :note, :issue_title, :description, :is_default,
                                           :enabled, :author_id, :position, :enabled_sharing, checklists: [])
  end
end

redmine_issue_templates/app/helpers/issue_templates_helper.rb
module IssueTemplatesHelper
  def project_tracker?(tracker, project)
    project.trackers.exists?(tracker)
  end

  def non_project_tracker_msg(flag)
    return '' if flag
    "<font class=\"non_project_tracker\">#{l(:unused_tracker_at_this_project)}</font>".html_safe
  end

  def template_target_trackers(project, issue_template)
    trackers = project.trackers
    trackers |= [issue_template.tracker] unless issue_template.tracker.blank?
    trackers.collect { |obj| [obj.name, obj.id] }
  end

  def options_for_template_pulldown(options)
    options.map do |option|
      text = option.try(:name).to_s
      content_tag_string(:option, text, option, true)
    end.join("\n").html_safe
  end
end

redmine_issue_templates/app/views/issue_templates/_form.html.erb
<%= error_messages_for 'issue_template' %>
<div class="box tabular box-white">
  <p><%= f.text_field :title, required: true, size: 80, label: l(:issue_template_name) %></p>

  <fieldset class="issue">
    <legend class="issue"><%= l(:label_applied_for_issue) %></legend>
    <p>
      <% if issue_template.tracker.blank? %>
          <%= f.select :tracker_id, template_target_trackers(project, issue_template),
                       required: true, label: l(:label_tracker), include_blank: true  %>
      <% else %>
          <%= f.select :tracker_id, template_target_trackers(project, issue_template),
                       required: true, label: l(:label_tracker), selected: issue_template.tracker.id %>
          <% unless project_tracker?(issue_template.tracker.id, project) %><br/>
              <%= non_project_tracker_msg(project_tracker?(issue_template.tracker.id, project)) %>
          <% end %>
      <% end %>
    </p>
    <p><%= f.text_field :issue_title, required: false, size: 80, label: l(:issue_title) %>
      <a class="icon icon-help template-help" title="<%= l(:help_for_this_field) %>"
         data-template-help-target="#issue_title_help_content"><%= l(:help_for_this_field) %></a>
      <br/>
      <span id="issue_title_help_content" class="issue_template help_content" style="display: none;">
        <%= l(:help_for_issue_title) %>
      </span>
    </p>
    <p>
      <%= f.text_area :description, cols: 78, rows: 12,
                      required: true,
                      label: l(:issue_description) %>
    </p>

    <!-- for Checklist -->
    <% if checklist_enabled %>
        <p id="checklist_form">
          <label>Checklist</label>
          <input type="text" id="checklist_text" class="edit-box">
          <span class="icon icon-add checklist-new-only save-new-by-button"
                onclick="addCheckList();">
          </span>
          <ul class='checklist' style='padding-left: 180px;'>
            <% issue_template.checklist.each_with_index do |content, i| %>
              <li id="checklist_<%= i %>">
                <span class="text">
                  <%= content %>
                  <a class="icon icon-del" href="javascript:void(0)" onclick="removeCheckList(this);"></a>
                </span>
                <input type="hidden" name="issue_template[checklists][]"
                       id="issue_template_checklist" value="<%= content %>">
              </li>
            <% end %>
          </ul>
        </p>
    <% end %>
  </fieldset>
  <p>
    <%= f.text_area :note, cols: 70, rows: 3,
                    required: false,
                    label: l(:issue_template_note) %>
  </p>

  <p><%= f.check_box :is_default, label: l(:field_is_default) %>
    <a class="icon icon-help template-help" title="<%= l(:help_for_this_field) %>"
       data-template-help-target="#isdefault_help_content">
      <%= l(:help_for_this_field) %>
    </a>
    <br/>
    <span id="isdefault_help_content" class="issue_template help_content" style="display: none;">
      <%= l(:label_isdefault_help_message) %>
    </span>
  </p>
  <p>
    <%= f.check_box :enabled, label: l(:label_enabled) %>
    <a class="icon icon-help template-help" title="<%= l(:help_for_this_field) %>"
       data-template-help-target="#enabled_help_content"><%= l(:help_for_this_field) %>
    </a>
    <br/>
    <span id="enabled_help_content" class="issue_template help_content" style="display: none;">
      <%= l(:label_enabled_help_message) %>
    </span>
  </p>

  <p>
    <%= f.check_box :enabled_sharing, label: l(:label_enabled_sharing) %>
    <a class="icon icon-help template-help" title="<%= l(:help_for_this_field) %>"
       data-template-help-target="#enabledsharing_help_content">
      <%= l(:help_for_this_field) %>
    </a>
    <br/>
    <span id="enabledsharing_help_content" class="issue_template help_content" style="display: none;">
      <%= l(:label_enabledshaing_help_message) %>
    </span>
  </p>

</div>

<%= wikitoolbar_for 'issue_template_description' %>


<script type="text/javascript">
  var checklist = $('.checklist');

  function removeCheckList(obj) {
    var target = obj.closest('li')
    target.remove();
  }

  function addCheckList() {
    var text = $('#checklist_text').val();
    if (text == '') return false;

    $('.checklist-item').each(function(i, elem) {
      e = $(elem)
      if ((text == e.val())) {
        return;
      }
    })
    addCheckListItem(text);
    $('#checklist_text').val('');
  }

  function addCheckListItem(value) {
    var li = $('<li>');
    var text = $('<span class="text">').text(value);
    var hidden = $("<input>", {
      type: 'hidden',
      id: 'issue_template_checklist',
      name: 'issue_template[checklists][]',
      class: 'checklist-item',
      value: value
    }).appendTo(li);

    var remove_link = $("<a>", {
      class: 'icon icon-del',
    });

    text.append(remove_link);
    li.append(text);
    checklist.append(li);

    $('body').on('click','.icon.icon-del', function() {
      removeCheckList(this);
    });
  }
</script>

redmine_issue_templates/app/views/issue_templates/_issue_template_link.html.erb
<% if authorize_for('issue_templates', 'show') %>
<h3><%= l(:issue_template) %></h3>
<ul>
  <li>
    <%= link_to(l(:label_list_templates),
    controller: 'issue_templates',
    action: 'index',
    project_id: @project) %>
  </li>
  <li>
    <%= link_to_if_authorized(l(:label_new_templates),
    { controller: 'issue_templates', action: 'new', project_id: @project }) %>
  </li>
</ul>
<%- end -%>

redmine_issue_templates/app/views/issue_templates/_template_pulldown.html.erb
<script type="text/javascript">
    var length = $('#issue_template > optgroup > option').length;
    if (length < 1) {
        $('#template_area').hide();
    } else {
        $('#template_area').show();
    }
</script>
<option value="">---</option>
<optgroup label="<%=h @tracker.name %>">
  <%= options_for_template_pulldown(grouped_options) %>
</optgroup>
<% if is_triggered_by_status.blank? || (is_triggered_by_status.present? && is_triggered_by_status == 'false') %>
    <script type="text/javascript">
        var load_url = '<%= url_for(controller: 'issue_templates', action: 'load', project_id: @project) %>';
        var should_replaced = '<%= should_replaced %>';
        var confirm_msg = "<%=h escape_javascript((l(:defaulf_template_loaded, tracker: @tracker))) %>";
        var confirmation = '<%=h l(:label_confirmation) %>';
        var general_text_Yes = '<%=h l(:general_text_Yes) %>';
        var general_text_No = '<%=h l(:general_text_No) %>';

        var templateNS = new ISSUE_TEMPLATE();
        templateNS.load_template(load_url, confirm_msg, should_replaced, false, confirmation, general_text_Yes, general_text_No);
    </script>
<% end %>

redmine_issue_templates/app/views/issue_templates/index.html.erb
<h2 class="template"><%=h "#{l(:issue_template)}" %></h2>
<%= render partial: "common/nodata", locals: { trackers: @project.trackers } %>
<div class="contextual issue_templates">
  <%= link_to_if_authorized(l(:label_new_templates),
                            { controller: 'issue_templates', action: 'new', project_id: @project },
                              class: 'icon icon-add') %>
</div>
<div style="clear:both;"></div>

<% if @notice -%>
  <div class="flash notice"><%= @notice -%></div>
<% end -%>


<% if @template_map.empty? %>
    <div class="template_box">
      <%= l(:no_issue_templates_for_this_project) %>
    </div>
<% end %>

<% @template_map.each_key do |tracker| %>
    <div class="template_box">
      <h3 class="template_tracker"><%= tracker.name %></h3>
      <%= non_project_tracker_msg(project_tracker?(tracker, @project)) %>

      <table class="list issues table-sortable">
        <thead>
        <tr>
          <th>#</th>
          <th><%= l(:issue_template_name) %></th>
          <th><%= l(:field_tracker) %></th>
          <th><%= l(:field_author) %></th>
          <th><%= l(:field_updated_on) %></th>
          <th><%= l(:field_is_default) %></th>
          <th><%= l(:label_enabled) %></th>
          <% if authorize_for('issue_templates', 'edit') %>
              <th><%=l(:button_sort)%></th>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <% @template_map[tracker].each do |issue_template| %>
            <tr class="<%= cycle('odd', 'even') %> issue_template issue">
              <td>
                <%= link_to h(issue_template.id),
                            { controller: :issue_templates, action: 'show',
                              id: issue_template.id, project_id: issue_template.project
                            },
                            { title: issue_template.note } %>
              </td>
              <td>
                <%= link_to h(issue_template.title),
                            { controller: 'issue_templates',
                              id: issue_template.id, action: 'show' },
                            { title: "#{html_escape(issue_template.note) }"} %>

                <div class="template_tooltip_wrapper">
                  <a class="icon template_tooltip" title="<%= l(:label_preview) %>"></a>
                  <div class="wiki template_tooltip_body">
                    <span class="title"><%= issue_template.title %></span>
                    <%= textilizable(issue_template.description) %>
                  </div>
                </div>
              </td>
              <td><%=h issue_template.tracker.name %></td>
              <td><%=h issue_template.author %></td>
              <td><%= format_time(issue_template.updated_on)%> </td>
              <td class="center"><%= checked_image issue_template.is_default? %></td>
              <td class="center"><%= checked_image issue_template.enabled? %></td>

              <% if authorize_for('issue_templates', 'edit') %>
                <td class="buttons">
                  <%= reorder_handle(issue_template,
                                     url: url_for(:controller => 'issue_templates',
                                                  :action => 'update', :id => issue_template.id,
                                                  :project_id => issue_template.project)) %>
                </td>
              <% end %>

            </tr>

        <% end %>
        </tbody>
      </table>
    </div>

  <%= javascript_tag do %>
    $(function() { $("table.table-sortable tbody").positionedItems(); });
  <% end %>
<% end %>


<% unless @inherit_templates.blank? %>
<h2 class="template"><%=h "#{l(:label_inherited_templates)}" %></h2>
  <div class="template_box">

        <table class="list issues">
          <thead>
          <tr>
            <th>#</th>
            <th><%= l(:issue_template_name) %></th>
            <th><%= l(:field_tracker) %></th>
            <th><%= l(:field_author) %></th>
            <th><%= l(:field_updated_on) %></th>
            <th><%= l(:field_is_default) %></th>
            <th><%= l(:label_enabled) %></th>
          </tr>
          </thead>
          <tbody>
          <% @inherit_templates.each do |issue_template| %>
              <tr class="<%= cycle('odd', 'even') %> issue_template issue">
                <td>
                  <%= link_to h(issue_template.id),
                              { controller: 'issue_templates',
                                action: 'show', id: issue_template.id,
                                project_id: issue_template.project_id },
                              { title: issue_template.note } %>
                </td>
                <td>
                  <%= link_to h(issue_template.title),
                              { controller: 'issue_templates',
                                project_id: issue_template.project_id,
                                id: issue_template.id, action: 'show' },
                              { title: "#{html_escape(issue_template.note)}" } %>

                  <div class="template_tooltip_wrapper">
                    <a class="icon template_tooltip" title="<%= l(:label_preview) %>"></a>
                    <div class="wiki template_tooltip_body">
                      <span class="title"><%=h issue_template.title %></span>
                      <%=h textilizable(issue_template.description) %>
                    </div>
                  </div>
                </td>
                <td><%=h issue_template.tracker.name %></td>
                <td><%=h issue_template.author %></td>
                <td><%=h format_time(issue_template.updated_on)%> </td>
                <td class="center"><%= checked_image issue_template.is_default? %></td>
                <td class="center"><%= checked_image issue_template.enabled? %></td>
              </tr>
              <tr class="<%= current_cycle %>" style="display: none;" id="template_description-<%= issue_template.id %>">
                <td class="description" colspan="8">
                  <div class="wiki"><%=h textilizable(issue_template.description) %></div></td>
              </tr>
          <% end %>
          </tbody>
        </table>
    </div>
 <% end %>

<% unless  @global_issue_templates.blank? %>
    <h2 class="template"><%=h "#{l(:global_issue_templates)}" %></h2>
    <div class="template_box">

      <% if apply_all_projects %>
          <p>
            <i class="issue_template icon settings"></i>
            <span class="issue_template help_content">
              <%= l(:note_apply_global_template_to_all_projects_setting_enabled) %><br/>
              <%= l(:note_project_local_template_override_global_template) %>
            </span>
          </p>
      <% end %>

      <%= l(:only_admin_can_associate_global_template) %>
      <table class="list issues">
        <thead>
        <tr>
          <th>#</th>
          <th><%= l(:issue_template_name) %></th>
          <th><%= l(:field_tracker) %></th>
          <th><%= l(:field_author) %></th>
          <th><%= l(:field_updated_on) %></th>
          <th><%= l(:field_is_default) %></th>
        </tr>
        </thead>
        <tbody>
        <% @global_issue_templates.each do |issue_template| %>
            <tr class="<%= cycle('odd', 'even') %> issue_template issue">
              <td>
                <% if User.current.admin? %>
                    <%= link_to h(issue_template.id),
                                { controller: 'global_issue_templates',
                                  action: 'show', id: issue_template.id, },
                                { title: issue_template.note } %>
                <% else %>
                    <%=h issue_template.id %>
                <% end %>
               </td>

              <td>
                <%= link_to h(issue_template.title),
                            { controller: 'global_issue_templates',
                              id: issue_template.id, action: 'show' },
                            { title: "#{html_escape(issue_template.note)}" } %>
                <div class="template_tooltip_wrapper">
                  <a class="icon template_tooltip" title="<%= l(:label_preview) %>"></a>
                  <div class="wiki template_tooltip_body">
                    <span class="title"><%=h issue_template.title %></span>
                    <%=h textilizable(issue_template.description) %>
                  </div>
                </div>
              </td>
              <td><%=h issue_template.tracker.name %></td>
              <td><%=h issue_template.author %></td>
              <td><%=h format_time(issue_template.updated_on)%> </td>
              <td class="center"><%= checked_image issue_template.is_default? %></td>
            </tr>
            <tr class="<%= current_cycle %>" style="display: none;" id="global_template_description-<%= issue_template.id %>">
              <td class="description" colspan="8">
                <div class="wiki"><%=h textilizable(issue_template.description) %></div></td>
            </tr>
        <% end %>
        </tbody>
      </table>

    </div>
<% end %>

<%= link_to l(:orphaned_templates, default: 'Orphaned Templates'), project_orphaned_templates_path, remote: true,
            id: 'orphaned_template_link', class: 'collapsible collapsed template_tooltip'
%>

<div id="orphaned_templates" style="display: none"></div>